# Generated by Django 4.2.6 on 2023-10-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='univer/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название курса')),
                ('description', models.TextField(verbose_name='описание курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Фото')),
                ('link', models.TextField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(verbose_name='Дата оплаты')),
                ('pay_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма оплаты')),
                ('pay_method', models.CharField(choices=[('cash', 'наличные'), ('transfer', 'безналичный расчет')], max_length=10, verbose_name='Способ оплаты')),
                ('payd_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univer.course')),
                ('payd_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univer.lesson')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
