# Generated by Django 4.2.6 on 2023-10-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='univer/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название курса')),
                ('description', models.TextField(verbose_name='описание курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Фото')),
                ('link', models.TextField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('pay_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма оплаты')),
                ('pay_method', models.CharField(choices=[('cash', 'наличные'), ('transfer', 'безналичный расчет')], max_length=10, verbose_name='Способ оплаты')),
                ('pay_id', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ID оплаты')),
                ('pay_status', models.CharField(blank=True, choices=[('success', 'оплачено'), ('not_paid', 'не оплачено'), ('error', 'ошибка оплаты')], default='not_paid', max_length=15, null=True, verbose_name='Статус оплаты')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
