# Generated by Django 4.2.6 on 2023-10-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='pay_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
