# Generated by Django 4.2.6 on 2023-10-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='user',
            new_name='pay_user',
        ),
    ]
