# Generated by Django 4.2.6 on 2023-10-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0003_alter_payments_pay_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('success', 'оплачено'), ('not_paid', 'не оплачено')], default='not_paid', max_length=15, null=True, verbose_name='Статус оплаты'),
        ),
    ]
